name: Slack Alert
description: A GitHub Action for sending build status alerts to a Slack channel.
inputs:
  success-prefix:
    description: The prefix to use in a success alert, defaults to 😎.
    required: false
  failure-prefix:
    description: The prefix to use in a failure alert, defaults to 😱.
    required: false
  webhook-url:
    description: The incoming webhook URL.
    required: true
  success:
    description: Specifies whether this is a success or failure alert.
    required: true
  action-label:
    description: Label of the action button. If provided along with `action-url`, the action button will be visible if `success` is `true`.
    required: false
  action-url:
    description: Link of the action button. If provided along with `action-label`, the action button will be visible if `success` is `true`.
    required: false
  verbose:
    description: Posts a more detailed version of the alert if enabled (defaults to `true`).
    required: false
outputs:
  response:
    description: The data of the Slack API request.
runs:
  using: node16
  main: dist/index.js
